#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1441446893                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Weather forecasts, simplified.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 :                                
your_link                                 :                      
your_city                                 :                                 
email_address                             : support@cumulusweatherapp.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Practical Design
    description                           : Cumulus is designed to not make you feel overwhelmed with data while also never leaving you unprepared. View all the forecast info from current conditions to daily forecasts up to 14 days in advance. Instantly and in one simple view.
    fontawesome_icon_name                 : ruler-combined
    
  - title                                 : Siri Shortcuts
    description                           : Record a custom phrase with Siri and get told everything you need to know about the weather around your location, like current temperatures and any precipitation in your area. All without lifting a finger!
    fontawesome_icon_name                 : microphone-alt

  - title                                 : Today Widget
    description                           : Check the weather at a glance without unlocking your phone with the Cumulus Today Widget. Look at what current weather conditions are and what's going to happen in the coming hours and up to four days in advance.
    fontawesome_icon_name                 : adjust

  - title                                 : Powered by the best
    description                           : Cumulus' forecasting abilities are powered by the Dark Sky servers. They allow Cumulus to get countless information about the weather like knowing when precipitation will start and end, or seeing future weather conditions.
    fontawesome_icon_name                 : broadcast-tower
    
  - title                                 : No Ads
    description                           : Cumulus gives you access to all the meteorological goodness with no obtrusive ads. View all the forecast data you want without being interrupted. 
    fontawesome_icon_name                 : eye-slash
    
  - title                                 : Pro Version
    description                           : For a one time purchase you can upgrade to Cumulus Pro for extra goodies including custom app icons, color themes, customization features, and more!
    fontawesome_icon_name                 : palette

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#ffffff"
feature_icons_background_color            : "#4361EE"

social_icons_foreground_color             : "#ffffff"
social_icons_background_color             : "#4361EE"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
